#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Details of a context to project association.

.PARAMETER ContextId
The ID of the context.
.PARAMETER ProjectId
The ID of the project.
.PARAMETER IsGlobalContext
Whether context is global.
.OUTPUTS

CustomFieldContextProjectMapping<PSCustomObject>
#>

function Initialize-CustomFieldContextProjectMapping {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ContextId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProjectId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsGlobalContext}
    )

    Process {
        'Creating PSCustomObject: PSJira => CustomFieldContextProjectMapping' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ContextId) {
            throw "invalid value for 'ContextId', 'ContextId' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "contextId" = ${ContextId}
            "projectId" = ${ProjectId}
            "isGlobalContext" = ${IsGlobalContext}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CustomFieldContextProjectMapping<PSCustomObject>

.DESCRIPTION

Convert from JSON to CustomFieldContextProjectMapping<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CustomFieldContextProjectMapping<PSCustomObject>
#>
function ConvertFrom-JsonToCustomFieldContextProjectMapping {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => CustomFieldContextProjectMapping' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CustomFieldContextProjectMapping
        $AllProperties = ("contextId", "projectId", "isGlobalContext")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'contextId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "contextId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'contextId' missing."
        } else {
            $ContextId = $JsonParameters.PSobject.Properties["contextId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "projectId"))) { #optional property not found
            $ProjectId = $null
        } else {
            $ProjectId = $JsonParameters.PSobject.Properties["projectId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isGlobalContext"))) { #optional property not found
            $IsGlobalContext = $null
        } else {
            $IsGlobalContext = $JsonParameters.PSobject.Properties["isGlobalContext"].value
        }

        $PSO = [PSCustomObject]@{
            "contextId" = ${ContextId}
            "projectId" = ${ProjectId}
            "isGlobalContext" = ${IsGlobalContext}
        }

        return $PSO
    }

}

