#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Details of a custom field option for a context.

.PARAMETER Id
The ID of the custom field option.
.PARAMETER Value
The value of the custom field option.
.PARAMETER Disabled
Whether the option is disabled.
.OUTPUTS

CustomFieldOptionUpdate<PSCustomObject>
#>

function Initialize-CustomFieldOptionUpdate {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Value},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Disabled}
    )

    Process {
        'Creating PSCustomObject: PSJira => CustomFieldOptionUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Id) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "value" = ${Value}
            "disabled" = ${Disabled}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CustomFieldOptionUpdate<PSCustomObject>

.DESCRIPTION

Convert from JSON to CustomFieldOptionUpdate<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CustomFieldOptionUpdate<PSCustomObject>
#>
function ConvertFrom-JsonToCustomFieldOptionUpdate {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => CustomFieldOptionUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CustomFieldOptionUpdate
        $AllProperties = ("id", "value", "disabled")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'id' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "value"))) { #optional property not found
            $Value = $null
        } else {
            $Value = $JsonParameters.PSobject.Properties["value"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "disabled"))) { #optional property not found
            $Disabled = $null
        } else {
            $Disabled = $JsonParameters.PSobject.Properties["disabled"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "value" = ${Value}
            "disabled" = ${Disabled}
        }

        return $PSO
    }

}

