#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The details of the gadget to update.

.PARAMETER Title
The title of the gadget.
.PARAMETER Color
The color of the gadget. Should be one of `blue`, `red`, `yellow`, `green`, `cyan`, `purple`, `gray`, or `white`.
.PARAMETER Position
No description available.
.OUTPUTS

DashboardGadgetUpdateRequest<PSCustomObject>
#>

function Initialize-DashboardGadgetUpdateRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Color},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Position}
    )

    Process {
        'Creating PSCustomObject: PSJira => DashboardGadgetUpdateRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "title" = ${Title}
            "color" = ${Color}
            "position" = ${Position}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DashboardGadgetUpdateRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to DashboardGadgetUpdateRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DashboardGadgetUpdateRequest<PSCustomObject>
#>
function ConvertFrom-JsonToDashboardGadgetUpdateRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => DashboardGadgetUpdateRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DashboardGadgetUpdateRequest
        $AllProperties = ("title", "color", "position")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "title"))) { #optional property not found
            $Title = $null
        } else {
            $Title = $JsonParameters.PSobject.Properties["title"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "color"))) { #optional property not found
            $Color = $null
        } else {
            $Color = $JsonParameters.PSobject.Properties["color"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "position"))) { #optional property not found
            $Position = $null
        } else {
            $Position = $JsonParameters.PSobject.Properties["position"].value
        }

        $PSO = [PSCustomObject]@{
            "title" = ${Title}
            "color" = ${Color}
            "position" = ${Position}
        }

        return $PSO
    }

}

