#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Defines the behavior of the option within the global context. If this property is set, even if set to an empty object, then the option is available in all projects.

.PARAMETER Attributes
Defines the behavior of the option in the global context.If notSelectable is set, the option cannot be set as the field's value. This is useful for archiving an option that has previously been selected but shouldn't be used anymore.If defaultValue is set, the option is selected by default.
.OUTPUTS

IssueFieldOptionScopeBeanGlobal<PSCustomObject>
#>

function Initialize-IssueFieldOptionScopeBeanGlobal {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("notSelectable", "defaultValue")]
        [String[]]
        ${Attributes}
    )

    Process {
        'Creating PSCustomObject: PSJira => IssueFieldOptionScopeBeanGlobal' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "attributes" = ${Attributes}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to IssueFieldOptionScopeBeanGlobal<PSCustomObject>

.DESCRIPTION

Convert from JSON to IssueFieldOptionScopeBeanGlobal<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

IssueFieldOptionScopeBeanGlobal<PSCustomObject>
#>
function ConvertFrom-JsonToIssueFieldOptionScopeBeanGlobal {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => IssueFieldOptionScopeBeanGlobal' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in IssueFieldOptionScopeBeanGlobal
        $AllProperties = ("attributes")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "attributes"))) { #optional property not found
            $Attributes = $null
        } else {
            $Attributes = $JsonParameters.PSobject.Properties["attributes"].value
        }

        $PSO = [PSCustomObject]@{
            "attributes" = ${Attributes}
        }

        return $PSO
    }

}

