#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Contains various characteristics of the performed expression evaluation.

.PARAMETER Complexity
No description available.
.PARAMETER Issues
No description available.
.OUTPUTS

JiraExpressionResultMeta<PSCustomObject>
#>

function Initialize-JiraExpressionResultMeta {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Complexity},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Issues}
    )

    Process {
        'Creating PSCustomObject: PSJira => JiraExpressionResultMeta' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "complexity" = ${Complexity}
            "issues" = ${Issues}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to JiraExpressionResultMeta<PSCustomObject>

.DESCRIPTION

Convert from JSON to JiraExpressionResultMeta<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

JiraExpressionResultMeta<PSCustomObject>
#>
function ConvertFrom-JsonToJiraExpressionResultMeta {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => JiraExpressionResultMeta' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in JiraExpressionResultMeta
        $AllProperties = ("complexity", "issues")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "complexity"))) { #optional property not found
            $Complexity = $null
        } else {
            $Complexity = $JsonParameters.PSobject.Properties["complexity"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "issues"))) { #optional property not found
            $Issues = $null
        } else {
            $Issues = $JsonParameters.PSobject.Properties["issues"].value
        }

        $PSO = [PSCustomObject]@{
            "complexity" = ${Complexity}
            "issues" = ${Issues}
        }

        return $PSO
    }

}

