#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The user details.

.PARAMETER Self
The URL of the user.
.PARAMETER Key
This property is no longer available. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
.PARAMETER Name
This property is no longer available. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
.PARAMETER Password
This property is no longer available. If the user has an Atlassian account, their password is not changed. If the user does not have an Atlassian account, they are sent an email asking them set up an account.
.PARAMETER EmailAddress
The email address for the user.
.PARAMETER DisplayName
This property is no longer available. If the user has an Atlassian account, their display name is not changed. If the user does not have an Atlassian account, they are sent an email asking them set up an account.
.PARAMETER ApplicationKeys
Deprecated, do not use.
.OUTPUTS

NewUserDetails<PSCustomObject>
#>

function Initialize-NewUserDetails {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Self},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Key},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Password},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EmailAddress},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DisplayName},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${ApplicationKeys}
    )

    Process {
        'Creating PSCustomObject: PSJira => NewUserDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $EmailAddress) {
            throw "invalid value for 'EmailAddress', 'EmailAddress' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "self" = ${Self}
            "key" = ${Key}
            "name" = ${Name}
            "password" = ${Password}
            "emailAddress" = ${EmailAddress}
            "displayName" = ${DisplayName}
            "applicationKeys" = ${ApplicationKeys}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to NewUserDetails<PSCustomObject>

.DESCRIPTION

Convert from JSON to NewUserDetails<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

NewUserDetails<PSCustomObject>
#>
function ConvertFrom-JsonToNewUserDetails {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => NewUserDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $NewUserDetailsAdditionalProperties = @{}

        # check if Json contains properties not defined in NewUserDetails
        $AllProperties = ("self", "key", "name", "password", "emailAddress", "displayName", "applicationKeys")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $NewUserDetailsAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'emailAddress' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "emailAddress"))) {
            throw "Error! JSON cannot be serialized due to the required property 'emailAddress' missing."
        } else {
            $EmailAddress = $JsonParameters.PSobject.Properties["emailAddress"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "self"))) { #optional property not found
            $Self = $null
        } else {
            $Self = $JsonParameters.PSobject.Properties["self"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "key"))) { #optional property not found
            $Key = $null
        } else {
            $Key = $JsonParameters.PSobject.Properties["key"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "password"))) { #optional property not found
            $Password = $null
        } else {
            $Password = $JsonParameters.PSobject.Properties["password"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "displayName"))) { #optional property not found
            $DisplayName = $null
        } else {
            $DisplayName = $JsonParameters.PSobject.Properties["displayName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "applicationKeys"))) { #optional property not found
            $ApplicationKeys = $null
        } else {
            $ApplicationKeys = $JsonParameters.PSobject.Properties["applicationKeys"].value
        }

        $PSO = [PSCustomObject]@{
            "self" = ${Self}
            "key" = ${Key}
            "name" = ${Name}
            "password" = ${Password}
            "emailAddress" = ${EmailAddress}
            "displayName" = ${DisplayName}
            "applicationKeys" = ${ApplicationKeys}
            "AdditionalProperties" = $NewUserDetailsAdditionalProperties
        }

        return $PSO
    }

}

