#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The project and issue type mapping.

.PARAMETER ProjectId
The ID of the project.
.PARAMETER IssueTypeId
The ID of the issue type.
.OUTPUTS

ProjectIssueTypeMapping<PSCustomObject>
#>

function Initialize-ProjectIssueTypeMapping {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProjectId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IssueTypeId}
    )

    Process {
        'Creating PSCustomObject: PSJira => ProjectIssueTypeMapping' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ProjectId) {
            throw "invalid value for 'ProjectId', 'ProjectId' cannot be null."
        }

        if ($null -eq $IssueTypeId) {
            throw "invalid value for 'IssueTypeId', 'IssueTypeId' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "projectId" = ${ProjectId}
            "issueTypeId" = ${IssueTypeId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ProjectIssueTypeMapping<PSCustomObject>

.DESCRIPTION

Convert from JSON to ProjectIssueTypeMapping<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ProjectIssueTypeMapping<PSCustomObject>
#>
function ConvertFrom-JsonToProjectIssueTypeMapping {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => ProjectIssueTypeMapping' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ProjectIssueTypeMapping
        $AllProperties = ("projectId", "issueTypeId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'projectId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "projectId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'projectId' missing."
        } else {
            $ProjectId = $JsonParameters.PSobject.Properties["projectId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "issueTypeId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'issueTypeId' missing."
        } else {
            $IssueTypeId = $JsonParameters.PSobject.Properties["issueTypeId"].value
        }

        $PSO = [PSCustomObject]@{
            "projectId" = ${ProjectId}
            "issueTypeId" = ${IssueTypeId}
        }

        return $PSO
    }

}

