#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The result of the task execution.

.PARAMETER ModifiedIssues
The IDs of the modified issues.
.PARAMETER UnmodifiedIssues
The IDs of the unchanged issues, those issues where errors prevent modification.
.PARAMETER Errors
No description available.
.OUTPUTS

TaskProgressBeanRemoveOptionFromIssuesResultResult<PSCustomObject>
#>

function Initialize-TaskProgressBeanRemoveOptionFromIssuesResultResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Int64[]]
        ${ModifiedIssues},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int64[]]
        ${UnmodifiedIssues},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Errors}
    )

    Process {
        'Creating PSCustomObject: PSJira => TaskProgressBeanRemoveOptionFromIssuesResultResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "modifiedIssues" = ${ModifiedIssues}
            "unmodifiedIssues" = ${UnmodifiedIssues}
            "errors" = ${Errors}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to TaskProgressBeanRemoveOptionFromIssuesResultResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to TaskProgressBeanRemoveOptionFromIssuesResultResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

TaskProgressBeanRemoveOptionFromIssuesResultResult<PSCustomObject>
#>
function ConvertFrom-JsonToTaskProgressBeanRemoveOptionFromIssuesResultResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => TaskProgressBeanRemoveOptionFromIssuesResultResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TaskProgressBeanRemoveOptionFromIssuesResultResult
        $AllProperties = ("modifiedIssues", "unmodifiedIssues", "errors")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "modifiedIssues"))) { #optional property not found
            $ModifiedIssues = $null
        } else {
            $ModifiedIssues = $JsonParameters.PSobject.Properties["modifiedIssues"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "unmodifiedIssues"))) { #optional property not found
            $UnmodifiedIssues = $null
        } else {
            $UnmodifiedIssues = $JsonParameters.PSobject.Properties["unmodifiedIssues"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "errors"))) { #optional property not found
            $Errors = $null
        } else {
            $Errors = $JsonParameters.PSobject.Properties["errors"].value
        }

        $PSO = [PSCustomObject]@{
            "modifiedIssues" = ${ModifiedIssues}
            "unmodifiedIssues" = ${UnmodifiedIssues}
            "errors" = ${Errors}
        }

        return $PSO
    }

}

