#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Details of workflow transition rules.

.PARAMETER WorkflowEntityId
The workflow ID.
.PARAMETER InvalidRules
List of workflow rule IDs that do not belong to the workflow or can not be found.
.PARAMETER ValidRules
List of valid workflow transition rules.
.OUTPUTS

WorkflowRulesSearchDetails<PSCustomObject>
#>

function Initialize-WorkflowRulesSearchDetails {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${WorkflowEntityId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${InvalidRules},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ValidRules}
    )

    Process {
        'Creating PSCustomObject: PSJira => WorkflowRulesSearchDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "workflowEntityId" = ${WorkflowEntityId}
            "invalidRules" = ${InvalidRules}
            "validRules" = ${ValidRules}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to WorkflowRulesSearchDetails<PSCustomObject>

.DESCRIPTION

Convert from JSON to WorkflowRulesSearchDetails<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

WorkflowRulesSearchDetails<PSCustomObject>
#>
function ConvertFrom-JsonToWorkflowRulesSearchDetails {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => WorkflowRulesSearchDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in WorkflowRulesSearchDetails
        $AllProperties = ("workflowEntityId", "invalidRules", "validRules")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "workflowEntityId"))) { #optional property not found
            $WorkflowEntityId = $null
        } else {
            $WorkflowEntityId = $JsonParameters.PSobject.Properties["workflowEntityId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "invalidRules"))) { #optional property not found
            $InvalidRules = $null
        } else {
            $InvalidRules = $JsonParameters.PSobject.Properties["invalidRules"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "validRules"))) { #optional property not found
            $ValidRules = $null
        } else {
            $ValidRules = $JsonParameters.PSobject.Properties["validRules"].value
        }

        $PSO = [PSCustomObject]@{
            "workflowEntityId" = ${WorkflowEntityId}
            "invalidRules" = ${InvalidRules}
            "validRules" = ${ValidRules}
        }

        return $PSO
    }

}

