#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'AppPropertiesApi' {
    Context 'Add-onPropertiesResourceDeleteAddonPropertyDelete' {
        It 'Test Add-onPropertiesResourceDeleteAddonPropertyDelete' {
            #$TestResult = Add-onPropertiesResourceDeleteAddonPropertyDelete -AddonKey "TEST_VALUE" -PropertyKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-onPropertiesResourceGetAddonPropertiesGet' {
        It 'Test Add-onPropertiesResourceGetAddonPropertiesGet' {
            #$TestResult = Add-onPropertiesResourceGetAddonPropertiesGet -AddonKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-onPropertiesResourceGetAddonPropertyGet' {
        It 'Test Add-onPropertiesResourceGetAddonPropertyGet' {
            #$TestResult = Add-onPropertiesResourceGetAddonPropertyGet -AddonKey "TEST_VALUE" -PropertyKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-onPropertiesResourcePutAddonPropertyPut' {
        It 'Test Add-onPropertiesResourcePutAddonPropertyPut' {
            #$TestResult = Add-onPropertiesResourcePutAddonPropertyPut -AddonKey "TEST_VALUE" -PropertyKey "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
