#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueCustomFieldConfigurationAppsApi' {
    Context 'Get-CustomFieldConfiguration' {
        It 'Test Get-CustomFieldConfiguration' {
            #$TestResult = Get-CustomFieldConfiguration -FieldIdOrKey "TEST_VALUE" -Id "TEST_VALUE" -FieldContextId "TEST_VALUE" -IssueId "TEST_VALUE" -ProjectKeyOrId "TEST_VALUE" -IssueTypeId "TEST_VALUE" -StartAt "TEST_VALUE" -MaxResults "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-CustomFieldConfiguration' {
        It 'Test Update-CustomFieldConfiguration' {
            #$TestResult = Update-CustomFieldConfiguration -FieldIdOrKey "TEST_VALUE" -CustomFieldConfigurations "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
