#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JiraExpressionsApi' {
    Context 'Invoke-AnalyseExpression' {
        It 'Test Invoke-AnalyseExpression' {
            #$TestResult = Invoke-AnalyseExpression -JiraExpressionForAnalysis "TEST_VALUE" -Check "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-EvaluateJiraExpression' {
        It 'Test Invoke-EvaluateJiraExpression' {
            #$TestResult = Invoke-EvaluateJiraExpression -JiraExpressionEvalRequestBean "TEST_VALUE" -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
