#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'LabelsApi' {
    Context 'Get-AllLabels' {
        It 'Test Get-AllLabels' {
            #$TestResult = Get-AllLabels -StartAt "TEST_VALUE" -MaxResults "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
