#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ActorsMap' {
    Context 'ActorsMap' {
        It 'Initialize-ActorsMap' {
            # a simple test to create an object
            #$NewObject = Initialize-ActorsMap -User "TEST_VALUE" -Group "TEST_VALUE" -GroupId "TEST_VALUE"
            #$NewObject | Should -BeOfType ActorsMap
            #$NewObject.property | Should -Be 0
        }
    }
}
