#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'AddGroupBean' {
    Context 'AddGroupBean' {
        It 'Initialize-AddGroupBean' {
            # a simple test to create an object
            #$NewObject = Initialize-AddGroupBean -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType AddGroupBean
            #$NewObject.property | Should -Be 0
        }
    }
}
