#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Application' {
    Context 'Application' {
        It 'Initialize-Application' {
            # a simple test to create an object
            #$NewObject = Initialize-Application -Type "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType Application
            #$NewObject.property | Should -Be 0
        }
    }
}
