#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'AttachmentArchive' {
    Context 'AttachmentArchive' {
        It 'Initialize-AttachmentArchive' {
            # a simple test to create an object
            #$NewObject = Initialize-AttachmentArchive -MoreAvailable "TEST_VALUE" -TotalNumberOfEntriesAvailable "TEST_VALUE" -TotalEntryCount "TEST_VALUE" -Entries "TEST_VALUE"
            #$NewObject | Should -BeOfType AttachmentArchive
            #$NewObject.property | Should -Be 0
        }
    }
}
