#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Attachment' {
    Context 'Attachment' {
        It 'Initialize-Attachment' {
            # a simple test to create an object
            #$NewObject = Initialize-Attachment -Self "TEST_VALUE" -Id "TEST_VALUE" -Filename "TEST_VALUE" -Author "TEST_VALUE" -Created "TEST_VALUE" -Size "TEST_VALUE" -MimeType "TEST_VALUE" -Content "TEST_VALUE" -Thumbnail "TEST_VALUE"
            #$NewObject | Should -BeOfType Attachment
            #$NewObject.property | Should -Be 0
        }
    }
}
