#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'AttachmentSettings' {
    Context 'AttachmentSettings' {
        It 'Initialize-AttachmentSettings' {
            # a simple test to create an object
            #$NewObject = Initialize-AttachmentSettings -Enabled "TEST_VALUE" -UploadLimit "TEST_VALUE"
            #$NewObject | Should -BeOfType AttachmentSettings
            #$NewObject.property | Should -Be 0
        }
    }
}
