#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'AvailableDashboardGadget' {
    Context 'AvailableDashboardGadget' {
        It 'Initialize-AvailableDashboardGadget' {
            # a simple test to create an object
            #$NewObject = Initialize-AvailableDashboardGadget -ModuleKey "TEST_VALUE" -Uri "TEST_VALUE" -Title "TEST_VALUE"
            #$NewObject | Should -BeOfType AvailableDashboardGadget
            #$NewObject.property | Should -Be 0
        }
    }
}
