#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Avatar' {
    Context 'Avatar' {
        It 'Initialize-Avatar' {
            # a simple test to create an object
            #$NewObject = Initialize-Avatar -Id "TEST_VALUE" -Owner "TEST_VALUE" -IsSystemAvatar "TEST_VALUE" -IsSelected "TEST_VALUE" -IsDeletable "TEST_VALUE" -FileName "TEST_VALUE" -Urls "TEST_VALUE"
            #$NewObject | Should -BeOfType Avatar
            #$NewObject.property | Should -Be 0
        }
    }
}
