#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'BulkIssuePropertyUpdateRequestFilter' {
    Context 'BulkIssuePropertyUpdateRequestFilter' {
        It 'Initialize-BulkIssuePropertyUpdateRequestFilter' {
            # a simple test to create an object
            #$NewObject = Initialize-BulkIssuePropertyUpdateRequestFilter -EntityIds "TEST_VALUE" -CurrentValue "TEST_VALUE" -HasProperty "TEST_VALUE"
            #$NewObject | Should -BeOfType BulkIssuePropertyUpdateRequestFilter
            #$NewObject.property | Should -Be 0
        }
    }
}
