#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'BulkIssueIsWatching' {
    Context 'BulkIssueIsWatching' {
        It 'Initialize-BulkIssueIsWatching' {
            # a simple test to create an object
            #$NewObject = Initialize-BulkIssueIsWatching -IssuesIsWatching "TEST_VALUE"
            #$NewObject | Should -BeOfType BulkIssueIsWatching
            #$NewObject.property | Should -Be 0
        }
    }
}
