#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'BulkProjectPermissions' {
    Context 'BulkProjectPermissions' {
        It 'Initialize-BulkProjectPermissions' {
            # a simple test to create an object
            #$NewObject = Initialize-BulkProjectPermissions -Issues "TEST_VALUE" -Projects "TEST_VALUE" -Permissions "TEST_VALUE"
            #$NewObject | Should -BeOfType BulkProjectPermissions
            #$NewObject.property | Should -Be 0
        }
    }
}
