#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ChangedWorklog' {
    Context 'ChangedWorklog' {
        It 'Initialize-ChangedWorklog' {
            # a simple test to create an object
            #$NewObject = Initialize-ChangedWorklog -WorklogId "TEST_VALUE" -UpdatedTime "TEST_VALUE" -Properties "TEST_VALUE"
            #$NewObject | Should -BeOfType ChangedWorklog
            #$NewObject.property | Should -Be 0
        }
    }
}
