#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ChangedValueBean' {
    Context 'ChangedValueBean' {
        It 'Initialize-ChangedValueBean' {
            # a simple test to create an object
            #$NewObject = Initialize-ChangedValueBean -FieldName "TEST_VALUE" -ChangedFrom "TEST_VALUE" -ChangedTo "TEST_VALUE"
            #$NewObject | Should -BeOfType ChangedValueBean
            #$NewObject.property | Should -Be 0
        }
    }
}
