#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ChangeFilterOwner' {
    Context 'ChangeFilterOwner' {
        It 'Initialize-ChangeFilterOwner' {
            # a simple test to create an object
            #$NewObject = Initialize-ChangeFilterOwner -AccountId "TEST_VALUE"
            #$NewObject | Should -BeOfType ChangeFilterOwner
            #$NewObject.property | Should -Be 0
        }
    }
}
