#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ChangedWorklogs' {
    Context 'ChangedWorklogs' {
        It 'Initialize-ChangedWorklogs' {
            # a simple test to create an object
            #$NewObject = Initialize-ChangedWorklogs -Values "TEST_VALUE" -Since "TEST_VALUE" -VarUntil "TEST_VALUE" -Self "TEST_VALUE" -NextPage "TEST_VALUE" -LastPage "TEST_VALUE"
            #$NewObject | Should -BeOfType ChangedWorklogs
            #$NewObject.property | Should -Be 0
        }
    }
}
