#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Changelog' {
    Context 'Changelog' {
        It 'Initialize-Changelog' {
            # a simple test to create an object
            #$NewObject = Initialize-Changelog -Id "TEST_VALUE" -Author "TEST_VALUE" -Created "TEST_VALUE" -Items "TEST_VALUE" -HistoryMetadata "TEST_VALUE"
            #$NewObject | Should -BeOfType Changelog
            #$NewObject.property | Should -Be 0
        }
    }
}
