#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CommentVisibility' {
    Context 'CommentVisibility' {
        It 'Initialize-CommentVisibility' {
            # a simple test to create an object
            #$NewObject = Initialize-CommentVisibility -Type "TEST_VALUE" -Value "TEST_VALUE" -Identifier "TEST_VALUE"
            #$NewObject | Should -BeOfType CommentVisibility
            #$NewObject.property | Should -Be 0
        }
    }
}
