#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ConfigurationTimeTrackingConfiguration' {
    Context 'ConfigurationTimeTrackingConfiguration' {
        It 'Initialize-ConfigurationTimeTrackingConfiguration' {
            # a simple test to create an object
            #$NewObject = Initialize-ConfigurationTimeTrackingConfiguration -WorkingHoursPerDay "TEST_VALUE" -WorkingDaysPerWeek "TEST_VALUE" -TimeFormat "TEST_VALUE" -DefaultUnit "TEST_VALUE"
            #$NewObject | Should -BeOfType ConfigurationTimeTrackingConfiguration
            #$NewObject.property | Should -Be 0
        }
    }
}
