#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ContainerForProjectFeatures' {
    Context 'ContainerForProjectFeatures' {
        It 'Initialize-ContainerForProjectFeatures' {
            # a simple test to create an object
            #$NewObject = Initialize-ContainerForProjectFeatures -Features "TEST_VALUE"
            #$NewObject | Should -BeOfType ContainerForProjectFeatures
            #$NewObject.property | Should -Be 0
        }
    }
}
