#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CreatedIssueWatchers' {
    Context 'CreatedIssueWatchers' {
        It 'Initialize-CreatedIssueWatchers' {
            # a simple test to create an object
            #$NewObject = Initialize-CreatedIssueWatchers -Status "TEST_VALUE" -ErrorCollection "TEST_VALUE"
            #$NewObject | Should -BeOfType CreatedIssueWatchers
            #$NewObject.property | Should -Be 0
        }
    }
}
