#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CreatePriorityDetails' {
    Context 'CreatePriorityDetails' {
        It 'Initialize-CreatePriorityDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-CreatePriorityDetails -Name "TEST_VALUE" -Description "TEST_VALUE" -IconUrl "TEST_VALUE" -StatusColor "TEST_VALUE"
            #$NewObject | Should -BeOfType CreatePriorityDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
