#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CreateWorkflowDetails' {
    Context 'CreateWorkflowDetails' {
        It 'Initialize-CreateWorkflowDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-CreateWorkflowDetails -Name "TEST_VALUE" -Description "TEST_VALUE" -Transitions "TEST_VALUE" -Statuses "TEST_VALUE"
            #$NewObject | Should -BeOfType CreateWorkflowDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
