#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CreateWorkflowTransitionRulesDetailsConditions' {
    Context 'CreateWorkflowTransitionRulesDetailsConditions' {
        It 'Initialize-CreateWorkflowTransitionRulesDetailsConditions' {
            # a simple test to create an object
            #$NewObject = Initialize-CreateWorkflowTransitionRulesDetailsConditions -Operator "TEST_VALUE" -Conditions "TEST_VALUE" -Type "TEST_VALUE" -Configuration "TEST_VALUE"
            #$NewObject | Should -BeOfType CreateWorkflowTransitionRulesDetailsConditions
            #$NewObject.property | Should -Be 0
        }
    }
}
