#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CustomFieldCreatedContextOptionsList' {
    Context 'CustomFieldCreatedContextOptionsList' {
        It 'Initialize-CustomFieldCreatedContextOptionsList' {
            # a simple test to create an object
            #$NewObject = Initialize-CustomFieldCreatedContextOptionsList -Options "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomFieldCreatedContextOptionsList
            #$NewObject.property | Should -Be 0
        }
    }
}
