#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CustomFieldContextDefaultValueForgeNumberField' {
    Context 'CustomFieldContextDefaultValueForgeNumberField' {
        It 'Initialize-CustomFieldContextDefaultValueForgeNumberField' {
            # a simple test to create an object
            #$NewObject = Initialize-CustomFieldContextDefaultValueForgeNumberField -ContextId "TEST_VALUE" -Number "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomFieldContextDefaultValueForgeNumberField
            #$NewObject.property | Should -Be 0
        }
    }
}
