#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CustomFieldContextDefaultValueMultipleVersionPicker' {
    Context 'CustomFieldContextDefaultValueMultipleVersionPicker' {
        It 'Initialize-CustomFieldContextDefaultValueMultipleVersionPicker' {
            # a simple test to create an object
            #$NewObject = Initialize-CustomFieldContextDefaultValueMultipleVersionPicker -VersionIds "TEST_VALUE" -VersionOrder "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomFieldContextDefaultValueMultipleVersionPicker
            #$NewObject.property | Should -Be 0
        }
    }
}
