#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CustomFieldContextDefaultValueForgeGroupField' {
    Context 'CustomFieldContextDefaultValueForgeGroupField' {
        It 'Initialize-CustomFieldContextDefaultValueForgeGroupField' {
            # a simple test to create an object
            #$NewObject = Initialize-CustomFieldContextDefaultValueForgeGroupField -ContextId "TEST_VALUE" -GroupId "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomFieldContextDefaultValueForgeGroupField
            #$NewObject.property | Should -Be 0
        }
    }
}
