#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CustomFieldContext' {
    Context 'CustomFieldContext' {
        It 'Initialize-CustomFieldContext' {
            # a simple test to create an object
            #$NewObject = Initialize-CustomFieldContext -Id "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -IsGlobalContext "TEST_VALUE" -IsAnyIssueType "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomFieldContext
            #$NewObject.property | Should -Be 0
        }
    }
}
