#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CustomFieldConfigurations' {
    Context 'CustomFieldConfigurations' {
        It 'Initialize-CustomFieldConfigurations' {
            # a simple test to create an object
            #$NewObject = Initialize-CustomFieldConfigurations -Configurations "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomFieldConfigurations
            #$NewObject.property | Should -Be 0
        }
    }
}
