#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CustomFieldContextDefaultValueURL' {
    Context 'CustomFieldContextDefaultValueURL' {
        It 'Initialize-CustomFieldContextDefaultValueURL' {
            # a simple test to create an object
            #$NewObject = Initialize-CustomFieldContextDefaultValueURL -ContextId "TEST_VALUE" -Url "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomFieldContextDefaultValueURL
            #$NewObject.property | Should -Be 0
        }
    }
}
