#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CustomFieldContextOption' {
    Context 'CustomFieldContextOption' {
        It 'Initialize-CustomFieldContextOption' {
            # a simple test to create an object
            #$NewObject = Initialize-CustomFieldContextOption -Id "TEST_VALUE" -Value "TEST_VALUE" -OptionId "TEST_VALUE" -Disabled "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomFieldContextOption
            #$NewObject.property | Should -Be 0
        }
    }
}
