#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'DashboardGadget' {
    Context 'DashboardGadget' {
        It 'Initialize-DashboardGadget' {
            # a simple test to create an object
            #$NewObject = Initialize-DashboardGadget -Id "TEST_VALUE" -ModuleKey "TEST_VALUE" -Uri "TEST_VALUE" -Color "TEST_VALUE" -Position "TEST_VALUE" -Title "TEST_VALUE"
            #$NewObject | Should -BeOfType DashboardGadget
            #$NewObject.property | Should -Be 0
        }
    }
}
