#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'DashboardDetails' {
    Context 'DashboardDetails' {
        It 'Initialize-DashboardDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-DashboardDetails -Name "TEST_VALUE" -Description "TEST_VALUE" -SharePermissions "TEST_VALUE" -EditPermissions "TEST_VALUE"
            #$NewObject | Should -BeOfType DashboardDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
