#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'DashboardGadgetUpdateRequest' {
    Context 'DashboardGadgetUpdateRequest' {
        It 'Initialize-DashboardGadgetUpdateRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-DashboardGadgetUpdateRequest -Title "TEST_VALUE" -Color "TEST_VALUE" -Position "TEST_VALUE"
            #$NewObject | Should -BeOfType DashboardGadgetUpdateRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
