#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'DashboardGadgetPosition' {
    Context 'DashboardGadgetPosition' {
        It 'Initialize-DashboardGadgetPosition' {
            # a simple test to create an object
            #$NewObject = Initialize-DashboardGadgetPosition -TheRowPositionOfTheGadget "TEST_VALUE" -TheColumnPositionOfTheGadget "TEST_VALUE"
            #$NewObject | Should -BeOfType DashboardGadgetPosition
            #$NewObject.property | Should -Be 0
        }
    }
}
