#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'FailedWebhooks' {
    Context 'FailedWebhooks' {
        It 'Initialize-FailedWebhooks' {
            # a simple test to create an object
            #$NewObject = Initialize-FailedWebhooks -Values "TEST_VALUE" -MaxResults "TEST_VALUE" -Next "TEST_VALUE"
            #$NewObject | Should -BeOfType FailedWebhooks
            #$NewObject.property | Should -Be 0
        }
    }
}
