#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'FieldMetadata' {
    Context 'FieldMetadata' {
        It 'Initialize-FieldMetadata' {
            # a simple test to create an object
            #$NewObject = Initialize-FieldMetadata -Required "TEST_VALUE" -Schema "TEST_VALUE" -Name "TEST_VALUE" -Key "TEST_VALUE" -AutoCompleteUrl "TEST_VALUE" -HasDefaultValue "TEST_VALUE" -Operations "TEST_VALUE" -AllowedValues "TEST_VALUE" -DefaultValue "TEST_VALUE" -Configuration "TEST_VALUE"
            #$NewObject | Should -BeOfType FieldMetadata
            #$NewObject.property | Should -Be 0
        }
    }
}
