#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'FieldReferenceData' {
    Context 'FieldReferenceData' {
        It 'Initialize-FieldReferenceData' {
            # a simple test to create an object
            #$NewObject = Initialize-FieldReferenceData -Value "TEST_VALUE" -DisplayName "TEST_VALUE" -Orderable "TEST_VALUE" -Searchable "TEST_VALUE" -Deprecated "TEST_VALUE" -DeprecatedSearcherKey "TEST_VALUE" -Auto "TEST_VALUE" -Cfid "TEST_VALUE" -Operators "TEST_VALUE" -Types "TEST_VALUE"
            #$NewObject | Should -BeOfType FieldReferenceData
            #$NewObject.property | Should -Be 0
        }
    }
}
