#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'FieldValueClause' {
    Context 'FieldValueClause' {
        It 'Initialize-FieldValueClause' {
            # a simple test to create an object
            #$NewObject = Initialize-FieldValueClause -Field "TEST_VALUE" -Operator "TEST_VALUE" -Operand "TEST_VALUE"
            #$NewObject | Should -BeOfType FieldValueClause
            #$NewObject.property | Should -Be 0
        }
    }
}
