#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'FieldConfigurationItem' {
    Context 'FieldConfigurationItem' {
        It 'Initialize-FieldConfigurationItem' {
            # a simple test to create an object
            #$NewObject = Initialize-FieldConfigurationItem -Id "TEST_VALUE" -Description "TEST_VALUE" -IsHidden "TEST_VALUE" -IsRequired "TEST_VALUE" -Renderer "TEST_VALUE"
            #$NewObject | Should -BeOfType FieldConfigurationItem
            #$NewObject.property | Should -Be 0
        }
    }
}
