#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'FieldDetails' {
    Context 'FieldDetails' {
        It 'Initialize-FieldDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-FieldDetails -Id "TEST_VALUE" -Key "TEST_VALUE" -Name "TEST_VALUE" -Custom "TEST_VALUE" -Orderable "TEST_VALUE" -Navigable "TEST_VALUE" -Searchable "TEST_VALUE" -ClauseNames "TEST_VALUE" -Scope "TEST_VALUE" -Schema "TEST_VALUE"
            #$NewObject | Should -BeOfType FieldDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
