#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'FieldConfigurationDetails' {
    Context 'FieldConfigurationDetails' {
        It 'Initialize-FieldConfigurationDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-FieldConfigurationDetails -Name "TEST_VALUE" -Description "TEST_VALUE"
            #$NewObject | Should -BeOfType FieldConfigurationDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
