#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'FieldConfigurationItemsDetails' {
    Context 'FieldConfigurationItemsDetails' {
        It 'Initialize-FieldConfigurationItemsDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-FieldConfigurationItemsDetails -FieldConfigurationItems "TEST_VALUE"
            #$NewObject | Should -BeOfType FieldConfigurationItemsDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
