#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'FoundGroup' {
    Context 'FoundGroup' {
        It 'Initialize-FoundGroup' {
            # a simple test to create an object
            #$NewObject = Initialize-FoundGroup -Name "TEST_VALUE" -Html "TEST_VALUE" -Labels "TEST_VALUE" -GroupId "TEST_VALUE"
            #$NewObject | Should -BeOfType FoundGroup
            #$NewObject.property | Should -Be 0
        }
    }
}
