#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'GroupLabel' {
    Context 'GroupLabel' {
        It 'Initialize-GroupLabel' {
            # a simple test to create an object
            #$NewObject = Initialize-GroupLabel -Text "TEST_VALUE" -Title "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType GroupLabel
            #$NewObject.property | Should -Be 0
        }
    }
}
