#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Icon' {
    Context 'Icon' {
        It 'Initialize-Icon' {
            # a simple test to create an object
            #$NewObject = Initialize-Icon -Url16x16 "TEST_VALUE" -Title "TEST_VALUE" -Link "TEST_VALUE"
            #$NewObject | Should -BeOfType Icon
            #$NewObject.property | Should -Be 0
        }
    }
}
