#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueTypeSchemeProjectsIssueTypeScheme' {
    Context 'IssueTypeSchemeProjectsIssueTypeScheme' {
        It 'Initialize-IssueTypeSchemeProjectsIssueTypeScheme' {
            # a simple test to create an object
            #$NewObject = Initialize-IssueTypeSchemeProjectsIssueTypeScheme -Id "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -DefaultIssueTypeId "TEST_VALUE" -IsDefault "TEST_VALUE"
            #$NewObject | Should -BeOfType IssueTypeSchemeProjectsIssueTypeScheme
            #$NewObject.property | Should -Be 0
        }
    }
}
