#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueBean' {
    Context 'IssueBean' {
        It 'Initialize-IssueBean' {
            # a simple test to create an object
            #$NewObject = Initialize-IssueBean -Expand "TEST_VALUE" -Id "TEST_VALUE" -Self "TEST_VALUE" -Key "TEST_VALUE" -RenderedFields "TEST_VALUE" -Properties "TEST_VALUE" -Names "TEST_VALUE" -Schema "TEST_VALUE" -Transitions "TEST_VALUE" -Operations "TEST_VALUE" -Editmeta "TEST_VALUE" -Changelog "TEST_VALUE" -VersionedRepresentations "TEST_VALUE" -FieldsToInclude "TEST_VALUE" -Fields "TEST_VALUE"
            #$NewObject | Should -BeOfType IssueBean
            #$NewObject.property | Should -Be 0
        }
    }
}
