#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueFieldOptionScopeBeanGlobal' {
    Context 'IssueFieldOptionScopeBeanGlobal' {
        It 'Initialize-IssueFieldOptionScopeBeanGlobal' {
            # a simple test to create an object
            #$NewObject = Initialize-IssueFieldOptionScopeBeanGlobal -Attributes "TEST_VALUE"
            #$NewObject | Should -BeOfType IssueFieldOptionScopeBeanGlobal
            #$NewObject.property | Should -Be 0
        }
    }
}
