#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssuesJqlMetaDataBean' {
    Context 'IssuesJqlMetaDataBean' {
        It 'Initialize-IssuesJqlMetaDataBean' {
            # a simple test to create an object
            #$NewObject = Initialize-IssuesJqlMetaDataBean -StartAt "TEST_VALUE" -MaxResults "TEST_VALUE" -Count "TEST_VALUE" -TotalCount "TEST_VALUE" -ValidationWarnings "TEST_VALUE"
            #$NewObject | Should -BeOfType IssuesJqlMetaDataBean
            #$NewObject.property | Should -Be 0
        }
    }
}
