#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueTypeInfo' {
    Context 'IssueTypeInfo' {
        It 'Initialize-IssueTypeInfo' {
            # a simple test to create an object
            #$NewObject = Initialize-IssueTypeInfo -Id "TEST_VALUE" -Name "TEST_VALUE" -AvatarId "TEST_VALUE"
            #$NewObject | Should -BeOfType IssueTypeInfo
            #$NewObject.property | Should -Be 0
        }
    }
}
