#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueSecurityLevelMember' {
    Context 'IssueSecurityLevelMember' {
        It 'Initialize-IssueSecurityLevelMember' {
            # a simple test to create an object
            #$NewObject = Initialize-IssueSecurityLevelMember -Id "TEST_VALUE" -IssueSecurityLevelId "TEST_VALUE" -Holder "TEST_VALUE"
            #$NewObject | Should -BeOfType IssueSecurityLevelMember
            #$NewObject.property | Should -Be 0
        }
    }
}
