#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueTypeScreenSchemeItem' {
    Context 'IssueTypeScreenSchemeItem' {
        It 'Initialize-IssueTypeScreenSchemeItem' {
            # a simple test to create an object
            #$NewObject = Initialize-IssueTypeScreenSchemeItem -IssueTypeScreenSchemeId "TEST_VALUE" -IssueTypeId "TEST_VALUE" -ScreenSchemeId "TEST_VALUE"
            #$NewObject | Should -BeOfType IssueTypeScreenSchemeItem
            #$NewObject.property | Should -Be 0
        }
    }
}
