#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueFilterForBulkPropertyDelete' {
    Context 'IssueFilterForBulkPropertyDelete' {
        It 'Initialize-IssueFilterForBulkPropertyDelete' {
            # a simple test to create an object
            #$NewObject = Initialize-IssueFilterForBulkPropertyDelete -EntityIds "TEST_VALUE" -CurrentValue "TEST_VALUE"
            #$NewObject | Should -BeOfType IssueFilterForBulkPropertyDelete
            #$NewObject.property | Should -Be 0
        }
    }
}
