#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueLinkInwardIssue' {
    Context 'IssueLinkInwardIssue' {
        It 'Initialize-IssueLinkInwardIssue' {
            # a simple test to create an object
            #$NewObject = Initialize-IssueLinkInwardIssue -Id "TEST_VALUE" -Key "TEST_VALUE" -Self "TEST_VALUE" -Fields "TEST_VALUE"
            #$NewObject | Should -BeOfType IssueLinkInwardIssue
            #$NewObject.property | Should -Be 0
        }
    }
}
