#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueTypeScreenSchemeDetails' {
    Context 'IssueTypeScreenSchemeDetails' {
        It 'Initialize-IssueTypeScreenSchemeDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-IssueTypeScreenSchemeDetails -Name "TEST_VALUE" -Description "TEST_VALUE" -IssueTypeMappings "TEST_VALUE"
            #$NewObject | Should -BeOfType IssueTypeScreenSchemeDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
