#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssuesUpdateBean' {
    Context 'IssuesUpdateBean' {
        It 'Initialize-IssuesUpdateBean' {
            # a simple test to create an object
            #$NewObject = Initialize-IssuesUpdateBean -IssueUpdates "TEST_VALUE"
            #$NewObject | Should -BeOfType IssuesUpdateBean
            #$NewObject.property | Should -Be 0
        }
    }
}
