#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueUpdateDetailsTransition' {
    Context 'IssueUpdateDetailsTransition' {
        It 'Initialize-IssueUpdateDetailsTransition' {
            # a simple test to create an object
            #$NewObject = Initialize-IssueUpdateDetailsTransition -Id "TEST_VALUE" -Name "TEST_VALUE" -To "TEST_VALUE" -HasScreen "TEST_VALUE" -IsGlobal "TEST_VALUE" -IsInitial "TEST_VALUE" -IsAvailable "TEST_VALUE" -IsConditional "TEST_VALUE" -Fields "TEST_VALUE" -Expand "TEST_VALUE" -Looped "TEST_VALUE"
            #$NewObject | Should -BeOfType IssueUpdateDetailsTransition
            #$NewObject.property | Should -Be 0
        }
    }
}
