#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssuesAndJQLQueries' {
    Context 'IssuesAndJQLQueries' {
        It 'Initialize-IssuesAndJQLQueries' {
            # a simple test to create an object
            #$NewObject = Initialize-IssuesAndJQLQueries -Jqls "TEST_VALUE" -IssueIds "TEST_VALUE"
            #$NewObject | Should -BeOfType IssuesAndJQLQueries
            #$NewObject.property | Should -Be 0
        }
    }
}
