#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueTypeScreenSchemeMappingDetails' {
    Context 'IssueTypeScreenSchemeMappingDetails' {
        It 'Initialize-IssueTypeScreenSchemeMappingDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-IssueTypeScreenSchemeMappingDetails -IssueTypeMappings "TEST_VALUE"
            #$NewObject | Should -BeOfType IssueTypeScreenSchemeMappingDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
