#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssuePickerSuggestionsIssueType' {
    Context 'IssuePickerSuggestionsIssueType' {
        It 'Initialize-IssuePickerSuggestionsIssueType' {
            # a simple test to create an object
            #$NewObject = Initialize-IssuePickerSuggestionsIssueType -Label "TEST_VALUE" -Sub "TEST_VALUE" -Id "TEST_VALUE" -Msg "TEST_VALUE" -Issues "TEST_VALUE"
            #$NewObject | Should -BeOfType IssuePickerSuggestionsIssueType
            #$NewObject.property | Should -Be 0
        }
    }
}
