#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueUpdateDetailsHistoryMetadata' {
    Context 'IssueUpdateDetailsHistoryMetadata' {
        It 'Initialize-IssueUpdateDetailsHistoryMetadata' {
            # a simple test to create an object
            #$NewObject = Initialize-IssueUpdateDetailsHistoryMetadata -Type "TEST_VALUE" -Description "TEST_VALUE" -DescriptionKey "TEST_VALUE" -ActivityDescription "TEST_VALUE" -ActivityDescriptionKey "TEST_VALUE" -EmailDescription "TEST_VALUE" -EmailDescriptionKey "TEST_VALUE" -Actor "TEST_VALUE" -Generator "TEST_VALUE" -Cause "TEST_VALUE" -ExtraData "TEST_VALUE"
            #$NewObject | Should -BeOfType IssueUpdateDetailsHistoryMetadata
            #$NewObject.property | Should -Be 0
        }
    }
}
