#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JiraExpressionEvalContextBean' {
    Context 'JiraExpressionEvalContextBean' {
        It 'Initialize-JiraExpressionEvalContextBean' {
            # a simple test to create an object
            #$NewObject = Initialize-JiraExpressionEvalContextBean -Issue "TEST_VALUE" -Issues "TEST_VALUE" -Project "TEST_VALUE" -Sprint "TEST_VALUE" -Board "TEST_VALUE" -ServiceDesk "TEST_VALUE" -CustomerRequest "TEST_VALUE" -Custom "TEST_VALUE"
            #$NewObject | Should -BeOfType JiraExpressionEvalContextBean
            #$NewObject.property | Should -Be 0
        }
    }
}
