#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JiraExpressionEvalContextBeanProject' {
    Context 'JiraExpressionEvalContextBeanProject' {
        It 'Initialize-JiraExpressionEvalContextBeanProject' {
            # a simple test to create an object
            #$NewObject = Initialize-JiraExpressionEvalContextBeanProject -Id "TEST_VALUE" -Key "TEST_VALUE"
            #$NewObject | Should -BeOfType JiraExpressionEvalContextBeanProject
            #$NewObject.property | Should -Be 0
        }
    }
}
