#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JiraExpressionValidationError' {
    Context 'JiraExpressionValidationError' {
        It 'Initialize-JiraExpressionValidationError' {
            # a simple test to create an object
            #$NewObject = Initialize-JiraExpressionValidationError -Line "TEST_VALUE" -Column "TEST_VALUE" -Expression "TEST_VALUE" -Message "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType JiraExpressionValidationError
            #$NewObject.property | Should -Be 0
        }
    }
}
