#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JiraExpressionEvaluationMetaDataBean' {
    Context 'JiraExpressionEvaluationMetaDataBean' {
        It 'Initialize-JiraExpressionEvaluationMetaDataBean' {
            # a simple test to create an object
            #$NewObject = Initialize-JiraExpressionEvaluationMetaDataBean -Complexity "TEST_VALUE" -Issues "TEST_VALUE"
            #$NewObject | Should -BeOfType JiraExpressionEvaluationMetaDataBean
            #$NewObject.property | Should -Be 0
        }
    }
}
