#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JiraExpressionEvaluationMetaDataBeanComplexity' {
    Context 'JiraExpressionEvaluationMetaDataBeanComplexity' {
        It 'Initialize-JiraExpressionEvaluationMetaDataBeanComplexity' {
            # a simple test to create an object
            #$NewObject = Initialize-JiraExpressionEvaluationMetaDataBeanComplexity -Steps "TEST_VALUE" -ExpensiveOperations "TEST_VALUE" -Beans "TEST_VALUE" -PrimitiveValues "TEST_VALUE"
            #$NewObject | Should -BeOfType JiraExpressionEvaluationMetaDataBeanComplexity
            #$NewObject.property | Should -Be 0
        }
    }
}
