#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JiraExpressionResult' {
    Context 'JiraExpressionResult' {
        It 'Initialize-JiraExpressionResult' {
            # a simple test to create an object
            #$NewObject = Initialize-JiraExpressionResult -Value "TEST_VALUE" -Meta "TEST_VALUE"
            #$NewObject | Should -BeOfType JiraExpressionResult
            #$NewObject.property | Should -Be 0
        }
    }
}
