#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JiraExpressionEvaluationMetaDataBeanIssues' {
    Context 'JiraExpressionEvaluationMetaDataBeanIssues' {
        It 'Initialize-JiraExpressionEvaluationMetaDataBeanIssues' {
            # a simple test to create an object
            #$NewObject = Initialize-JiraExpressionEvaluationMetaDataBeanIssues -Jql "TEST_VALUE"
            #$NewObject | Should -BeOfType JiraExpressionEvaluationMetaDataBeanIssues
            #$NewObject.property | Should -Be 0
        }
    }
}
