#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JqlQueryOrderByClause' {
    Context 'JqlQueryOrderByClause' {
        It 'Initialize-JqlQueryOrderByClause' {
            # a simple test to create an object
            #$NewObject = Initialize-JqlQueryOrderByClause -Fields "TEST_VALUE"
            #$NewObject | Should -BeOfType JqlQueryOrderByClause
            #$NewObject.property | Should -Be 0
        }
    }
}
