#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JqlQueryToSanitize' {
    Context 'JqlQueryToSanitize' {
        It 'Initialize-JqlQueryToSanitize' {
            # a simple test to create an object
            #$NewObject = Initialize-JqlQueryToSanitize -AccountId "TEST_VALUE" -Query "TEST_VALUE"
            #$NewObject | Should -BeOfType JqlQueryToSanitize
            #$NewObject.property | Should -Be 0
        }
    }
}
