#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JQLQueryWithUnknownUsers' {
    Context 'JQLQueryWithUnknownUsers' {
        It 'Initialize-JQLQueryWithUnknownUsers' {
            # a simple test to create an object
            #$NewObject = Initialize-JQLQueryWithUnknownUsers -OriginalQuery "TEST_VALUE" -ConvertedQuery "TEST_VALUE"
            #$NewObject | Should -BeOfType JQLQueryWithUnknownUsers
            #$NewObject.property | Should -Be 0
        }
    }
}
