#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JqlQueryField' {
    Context 'JqlQueryField' {
        It 'Initialize-JqlQueryField' {
            # a simple test to create an object
            #$NewObject = Initialize-JqlQueryField -Name "TEST_VALUE" -Property "TEST_VALUE"
            #$NewObject | Should -BeOfType JqlQueryField
            #$NewObject.property | Should -Be 0
        }
    }
}
