#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JqlQueryClauseOperand' {
    Context 'JqlQueryClauseOperand' {
        It 'Initialize-JqlQueryClauseOperand' {
            # a simple test to create an object
            #$NewObject = Initialize-JqlQueryClauseOperand -Values "TEST_VALUE" -Value "TEST_VALUE" -VarFunction "TEST_VALUE" -Arguments "TEST_VALUE" -Keyword "TEST_VALUE"
            #$NewObject | Should -BeOfType JqlQueryClauseOperand
            #$NewObject.property | Should -Be 0
        }
    }
}
