#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'JsonTypeBean' {
    Context 'JsonTypeBean' {
        It 'Initialize-JsonTypeBean' {
            # a simple test to create an object
            #$NewObject = Initialize-JsonTypeBean -Type "TEST_VALUE" -Items "TEST_VALUE" -System "TEST_VALUE" -Custom "TEST_VALUE" -CustomId "TEST_VALUE" -Configuration "TEST_VALUE"
            #$NewObject | Should -BeOfType JsonTypeBean
            #$NewObject.property | Should -Be 0
        }
    }
}
