#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'License' {
    Context 'License' {
        It 'Initialize-License' {
            # a simple test to create an object
            #$NewObject = Initialize-License -Applications "TEST_VALUE"
            #$NewObject | Should -BeOfType License
            #$NewObject.property | Should -Be 0
        }
    }
}
