#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'LinkGroup' {
    Context 'LinkGroup' {
        It 'Initialize-LinkGroup' {
            # a simple test to create an object
            #$NewObject = Initialize-LinkGroup -Id "TEST_VALUE" -StyleClass "TEST_VALUE" -Header "TEST_VALUE" -Weight "TEST_VALUE" -Links "TEST_VALUE" -Groups "TEST_VALUE"
            #$NewObject | Should -BeOfType LinkGroup
            #$NewObject.property | Should -Be 0
        }
    }
}
