#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Locale' {
    Context 'Locale' {
        It 'Initialize-Locale' {
            # a simple test to create an object
            #$NewObject = Initialize-Locale -Locale "TEST_VALUE"
            #$NewObject | Should -BeOfType Locale
            #$NewObject.property | Should -Be 0
        }
    }
}
