#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'MoveFieldBean' {
    Context 'MoveFieldBean' {
        It 'Initialize-MoveFieldBean' {
            # a simple test to create an object
            #$NewObject = Initialize-MoveFieldBean -After "TEST_VALUE" -Position "TEST_VALUE"
            #$NewObject | Should -BeOfType MoveFieldBean
            #$NewObject.property | Should -Be 0
        }
    }
}
