#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'MultiIssueEntityProperties' {
    Context 'MultiIssueEntityProperties' {
        It 'Initialize-MultiIssueEntityProperties' {
            # a simple test to create an object
            #$NewObject = Initialize-MultiIssueEntityProperties -Issues "TEST_VALUE"
            #$NewObject | Should -BeOfType MultiIssueEntityProperties
            #$NewObject.property | Should -Be 0
        }
    }
}
