#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'NotificationSchemeNotificationDetails' {
    Context 'NotificationSchemeNotificationDetails' {
        It 'Initialize-NotificationSchemeNotificationDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-NotificationSchemeNotificationDetails -NotificationType "TEST_VALUE" -Parameter "TEST_VALUE"
            #$NewObject | Should -BeOfType NotificationSchemeNotificationDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
