#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'NotificationTo' {
    Context 'NotificationTo' {
        It 'Initialize-NotificationTo' {
            # a simple test to create an object
            #$NewObject = Initialize-NotificationTo -Reporter "TEST_VALUE" -Assignee "TEST_VALUE" -Watchers "TEST_VALUE" -Voters "TEST_VALUE" -Users "TEST_VALUE" -Groups "TEST_VALUE" -GroupIds "TEST_VALUE"
            #$NewObject | Should -BeOfType NotificationTo
            #$NewObject.property | Should -Be 0
        }
    }
}
