#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'PagedListUserDetailsApplicationUser' {
    Context 'PagedListUserDetailsApplicationUser' {
        It 'Initialize-PagedListUserDetailsApplicationUser' {
            # a simple test to create an object
            #$NewObject = Initialize-PagedListUserDetailsApplicationUser -Size "TEST_VALUE" -Items "TEST_VALUE" -MaxResults "TEST_VALUE" -StartIndex "TEST_VALUE" -EndIndex "TEST_VALUE"
            #$NewObject | Should -BeOfType PagedListUserDetailsApplicationUser
            #$NewObject.property | Should -Be 0
        }
    }
}
