#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'PageOfDashboards' {
    Context 'PageOfDashboards' {
        It 'Initialize-PageOfDashboards' {
            # a simple test to create an object
            #$NewObject = Initialize-PageOfDashboards -StartAt "TEST_VALUE" -MaxResults "TEST_VALUE" -Total "TEST_VALUE" -Prev "TEST_VALUE" -Next "TEST_VALUE" -Dashboards "TEST_VALUE"
            #$NewObject | Should -BeOfType PageOfDashboards
            #$NewObject.property | Should -Be 0
        }
    }
}
