#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'PageBeanUser' {
    Context 'PageBeanUser' {
        It 'Initialize-PageBeanUser' {
            # a simple test to create an object
            #$NewObject = Initialize-PageBeanUser -Self "TEST_VALUE" -NextPage "TEST_VALUE" -MaxResults "TEST_VALUE" -StartAt "TEST_VALUE" -Total "TEST_VALUE" -IsLast "TEST_VALUE" -Values "TEST_VALUE"
            #$NewObject | Should -BeOfType PageBeanUser
            #$NewObject.property | Should -Be 0
        }
    }
}
