#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Permissions' {
    Context 'Permissions' {
        It 'Initialize-Permissions' {
            # a simple test to create an object
            #$NewObject = Initialize-Permissions -Permissions "TEST_VALUE"
            #$NewObject | Should -BeOfType Permissions
            #$NewObject.property | Should -Be 0
        }
    }
}
