#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'PermissionHolder' {
    Context 'PermissionHolder' {
        It 'Initialize-PermissionHolder' {
            # a simple test to create an object
            #$NewObject = Initialize-PermissionHolder -Type "TEST_VALUE" -Parameter "TEST_VALUE" -Value "TEST_VALUE" -Expand "TEST_VALUE"
            #$NewObject | Should -BeOfType PermissionHolder
            #$NewObject.property | Should -Be 0
        }
    }
}
