#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'PermittedProjects' {
    Context 'PermittedProjects' {
        It 'Initialize-PermittedProjects' {
            # a simple test to create an object
            #$NewObject = Initialize-PermittedProjects -Projects "TEST_VALUE"
            #$NewObject | Should -BeOfType PermittedProjects
            #$NewObject.property | Should -Be 0
        }
    }
}
