#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'PermissionGrants' {
    Context 'PermissionGrants' {
        It 'Initialize-PermissionGrants' {
            # a simple test to create an object
            #$NewObject = Initialize-PermissionGrants -Permissions "TEST_VALUE" -Expand "TEST_VALUE"
            #$NewObject | Should -BeOfType PermissionGrants
            #$NewObject.property | Should -Be 0
        }
    }
}
