#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Priority' {
    Context 'Priority' {
        It 'Initialize-Priority' {
            # a simple test to create an object
            #$NewObject = Initialize-Priority -Self "TEST_VALUE" -StatusColor "TEST_VALUE" -Description "TEST_VALUE" -IconUrl "TEST_VALUE" -Name "TEST_VALUE" -Id "TEST_VALUE" -IsDefault "TEST_VALUE"
            #$NewObject | Should -BeOfType Priority
            #$NewObject.property | Should -Be 0
        }
    }
}
