#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ProjectIdentifierBean' {
    Context 'ProjectIdentifierBean' {
        It 'Initialize-ProjectIdentifierBean' {
            # a simple test to create an object
            #$NewObject = Initialize-ProjectIdentifierBean -Id "TEST_VALUE" -Key "TEST_VALUE"
            #$NewObject | Should -BeOfType ProjectIdentifierBean
            #$NewObject.property | Should -Be 0
        }
    }
}
