#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ProjectDetails' {
    Context 'ProjectDetails' {
        It 'Initialize-ProjectDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-ProjectDetails -Self "TEST_VALUE" -Id "TEST_VALUE" -Key "TEST_VALUE" -Name "TEST_VALUE" -ProjectTypeKey "TEST_VALUE" -Simplified "TEST_VALUE" -AvatarUrls "TEST_VALUE" -ProjectCategory "TEST_VALUE"
            #$NewObject | Should -BeOfType ProjectDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
