#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ProjectComponent' {
    Context 'ProjectComponent' {
        It 'Initialize-ProjectComponent' {
            # a simple test to create an object
            #$NewObject = Initialize-ProjectComponent -Self "TEST_VALUE" -Id "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -Lead "TEST_VALUE" -LeadUserName "TEST_VALUE" -LeadAccountId "TEST_VALUE" -AssigneeType "TEST_VALUE" -Assignee "TEST_VALUE" -RealAssigneeType "TEST_VALUE" -RealAssignee "TEST_VALUE" -IsAssigneeTypeValid "TEST_VALUE" -Project "TEST_VALUE" -ProjectId "TEST_VALUE"
            #$NewObject | Should -BeOfType ProjectComponent
            #$NewObject.property | Should -Be 0
        }
    }
}
