#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ProjectInsight' {
    Context 'ProjectInsight' {
        It 'Initialize-ProjectInsight' {
            # a simple test to create an object
            #$NewObject = Initialize-ProjectInsight -TotalIssueCount "TEST_VALUE" -LastIssueUpdateTime "TEST_VALUE"
            #$NewObject | Should -BeOfType ProjectInsight
            #$NewObject.property | Should -Be 0
        }
    }
}
