#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ProjectRoleActorsUpdateBean' {
    Context 'ProjectRoleActorsUpdateBean' {
        It 'Initialize-ProjectRoleActorsUpdateBean' {
            # a simple test to create an object
            #$NewObject = Initialize-ProjectRoleActorsUpdateBean -Id "TEST_VALUE" -CategorisedActors "TEST_VALUE"
            #$NewObject | Should -BeOfType ProjectRoleActorsUpdateBean
            #$NewObject.property | Should -Be 0
        }
    }
}
