#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ProjectFeature' {
    Context 'ProjectFeature' {
        It 'Initialize-ProjectFeature' {
            # a simple test to create an object
            #$NewObject = Initialize-ProjectFeature -ProjectId "TEST_VALUE" -State "TEST_VALUE" -ToggleLocked "TEST_VALUE" -Feature "TEST_VALUE" -Prerequisites "TEST_VALUE" -LocalisedName "TEST_VALUE" -LocalisedDescription "TEST_VALUE" -ImageUri "TEST_VALUE"
            #$NewObject | Should -BeOfType ProjectFeature
            #$NewObject.property | Should -Be 0
        }
    }
}
