#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'PropertyKeys' {
    Context 'PropertyKeys' {
        It 'Initialize-PropertyKeys' {
            # a simple test to create an object
            #$NewObject = Initialize-PropertyKeys -Keys "TEST_VALUE"
            #$NewObject | Should -BeOfType PropertyKeys
            #$NewObject.property | Should -Be 0
        }
    }
}
