#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'PublishDraftWorkflowScheme' {
    Context 'PublishDraftWorkflowScheme' {
        It 'Initialize-PublishDraftWorkflowScheme' {
            # a simple test to create an object
            #$NewObject = Initialize-PublishDraftWorkflowScheme -StatusMappings "TEST_VALUE"
            #$NewObject | Should -BeOfType PublishDraftWorkflowScheme
            #$NewObject.property | Should -Be 0
        }
    }
}
