#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'RemoteIssueLinkIdentifies' {
    Context 'RemoteIssueLinkIdentifies' {
        It 'Initialize-RemoteIssueLinkIdentifies' {
            # a simple test to create an object
            #$NewObject = Initialize-RemoteIssueLinkIdentifies -Id "TEST_VALUE" -Self "TEST_VALUE"
            #$NewObject | Should -BeOfType RemoteIssueLinkIdentifies
            #$NewObject.property | Should -Be 0
        }
    }
}
