#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'RemoteObject' {
    Context 'RemoteObject' {
        It 'Initialize-RemoteObject' {
            # a simple test to create an object
            #$NewObject = Initialize-RemoteObject -Url "TEST_VALUE" -Title "TEST_VALUE" -Summary "TEST_VALUE" -Icon "TEST_VALUE" -Status "TEST_VALUE"
            #$NewObject | Should -BeOfType RemoteObject
            #$NewObject.property | Should -Be 0
        }
    }
}
