#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ReorderIssuePriorities' {
    Context 'ReorderIssuePriorities' {
        It 'Initialize-ReorderIssuePriorities' {
            # a simple test to create an object
            #$NewObject = Initialize-ReorderIssuePriorities -Ids "TEST_VALUE" -After "TEST_VALUE" -Position "TEST_VALUE"
            #$NewObject | Should -BeOfType ReorderIssuePriorities
            #$NewObject.property | Should -Be 0
        }
    }
}
