#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ResolutionJsonBean' {
    Context 'ResolutionJsonBean' {
        It 'Initialize-ResolutionJsonBean' {
            # a simple test to create an object
            #$NewObject = Initialize-ResolutionJsonBean -Self "TEST_VALUE" -Id "TEST_VALUE" -Description "TEST_VALUE" -IconUrl "TEST_VALUE" -Name "TEST_VALUE" -Default "TEST_VALUE"
            #$NewObject | Should -BeOfType ResolutionJsonBean
            #$NewObject.property | Should -Be 0
        }
    }
}
