#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'SanitizedJqlQueryErrors' {
    Context 'SanitizedJqlQueryErrors' {
        It 'Initialize-SanitizedJqlQueryErrors' {
            # a simple test to create an object
            #$NewObject = Initialize-SanitizedJqlQueryErrors -ErrorMessages "TEST_VALUE" -Errors "TEST_VALUE" -Status "TEST_VALUE"
            #$NewObject | Should -BeOfType SanitizedJqlQueryErrors
            #$NewObject.property | Should -Be 0
        }
    }
}
