#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ScreenSchemeDetailsScreens' {
    Context 'ScreenSchemeDetailsScreens' {
        It 'Initialize-ScreenSchemeDetailsScreens' {
            # a simple test to create an object
            #$NewObject = Initialize-ScreenSchemeDetailsScreens -Edit "TEST_VALUE" -Create "TEST_VALUE" -View "TEST_VALUE" -Default "TEST_VALUE"
            #$NewObject | Should -BeOfType ScreenSchemeDetailsScreens
            #$NewObject.property | Should -Be 0
        }
    }
}
