#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ScreenSchemeId' {
    Context 'ScreenSchemeId' {
        It 'Initialize-ScreenSchemeId' {
            # a simple test to create an object
            #$NewObject = Initialize-ScreenSchemeId -Id "TEST_VALUE"
            #$NewObject | Should -BeOfType ScreenSchemeId
            #$NewObject.property | Should -Be 0
        }
    }
}
