#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ScreenScope' {
    Context 'ScreenScope' {
        It 'Initialize-ScreenScope' {
            # a simple test to create an object
            #$NewObject = Initialize-ScreenScope -Type "TEST_VALUE" -Project "TEST_VALUE"
            #$NewObject | Should -BeOfType ScreenScope
            #$NewObject.property | Should -Be 0
        }
    }
}
