#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ScreenWithTab' {
    Context 'ScreenWithTab' {
        It 'Initialize-ScreenWithTab' {
            # a simple test to create an object
            #$NewObject = Initialize-ScreenWithTab -Id "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -Scope "TEST_VALUE" -Tab "TEST_VALUE"
            #$NewObject | Should -BeOfType ScreenWithTab
            #$NewObject.property | Should -Be 0
        }
    }
}
