#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ScreenSchemeDetails' {
    Context 'ScreenSchemeDetails' {
        It 'Initialize-ScreenSchemeDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-ScreenSchemeDetails -Name "TEST_VALUE" -Description "TEST_VALUE" -Screens "TEST_VALUE"
            #$NewObject | Should -BeOfType ScreenSchemeDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
