#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'SearchResults' {
    Context 'SearchResults' {
        It 'Initialize-SearchResults' {
            # a simple test to create an object
            #$NewObject = Initialize-SearchResults -Expand "TEST_VALUE" -StartAt "TEST_VALUE" -MaxResults "TEST_VALUE" -Total "TEST_VALUE" -Issues "TEST_VALUE" -WarningMessages "TEST_VALUE" -Names "TEST_VALUE" -Schema "TEST_VALUE"
            #$NewObject | Should -BeOfType SearchResults
            #$NewObject.property | Should -Be 0
        }
    }
}
