#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'SharePermissionProject' {
    Context 'SharePermissionProject' {
        It 'Initialize-SharePermissionProject' {
            # a simple test to create an object
            #$NewObject = Initialize-SharePermissionProject -Expand "TEST_VALUE" -Self "TEST_VALUE" -Id "TEST_VALUE" -Key "TEST_VALUE" -Description "TEST_VALUE" -Lead "TEST_VALUE" -Components "TEST_VALUE" -IssueTypes "TEST_VALUE" -Url "TEST_VALUE" -Email "TEST_VALUE" -AssigneeType "TEST_VALUE" -Versions "TEST_VALUE" -Name "TEST_VALUE" -Roles "TEST_VALUE" -AvatarUrls "TEST_VALUE" -ProjectCategory "TEST_VALUE" -ProjectTypeKey "TEST_VALUE" -Simplified "TEST_VALUE" -Style "TEST_VALUE" -Favourite "TEST_VALUE" -IsPrivate "TEST_VALUE" -IssueTypeHierarchy "TEST_VALUE" -Permissions "TEST_VALUE" -Properties "TEST_VALUE" -Uuid "TEST_VALUE" -Insight "TEST_VALUE" -Deleted "TEST_VALUE" -RetentionTillDate "TEST_VALUE" -DeletedDate "TEST_VALUE" -DeletedBy "TEST_VALUE" -Archived "TEST_VALUE" -ArchivedDate "TEST_VALUE" -ArchivedBy "TEST_VALUE" -LandingPageInfo "TEST_VALUE"
            #$NewObject | Should -BeOfType SharePermissionProject
            #$NewObject.property | Should -Be 0
        }
    }
}
