#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'SharePermissionRole' {
    Context 'SharePermissionRole' {
        It 'Initialize-SharePermissionRole' {
            # a simple test to create an object
            #$NewObject = Initialize-SharePermissionRole -Self "TEST_VALUE" -Name "TEST_VALUE" -Id "TEST_VALUE" -Description "TEST_VALUE" -Actors "TEST_VALUE" -Scope "TEST_VALUE" -TranslatedName "TEST_VALUE" -CurrentUserRole "TEST_VALUE" -Default "TEST_VALUE" -Admin "TEST_VALUE" -RoleConfigurable "TEST_VALUE"
            #$NewObject | Should -BeOfType SharePermissionRole
            #$NewObject.property | Should -Be 0
        }
    }
}
