#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'SharePermission' {
    Context 'SharePermission' {
        It 'Initialize-SharePermission' {
            # a simple test to create an object
            #$NewObject = Initialize-SharePermission -Id "TEST_VALUE" -Type "TEST_VALUE" -Project "TEST_VALUE" -Role "TEST_VALUE" -Group "TEST_VALUE" -User "TEST_VALUE"
            #$NewObject | Should -BeOfType SharePermission
            #$NewObject.property | Should -Be 0
        }
    }
}
