#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'SimpleErrorCollection' {
    Context 'SimpleErrorCollection' {
        It 'Initialize-SimpleErrorCollection' {
            # a simple test to create an object
            #$NewObject = Initialize-SimpleErrorCollection -Errors "TEST_VALUE" -ErrorMessages "TEST_VALUE" -HttpStatusCode "TEST_VALUE"
            #$NewObject | Should -BeOfType SimpleErrorCollection
            #$NewObject.property | Should -Be 0
        }
    }
}
