#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'StatusCreateRequest' {
    Context 'StatusCreateRequest' {
        It 'Initialize-StatusCreateRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-StatusCreateRequest -Statuses "TEST_VALUE" -Scope "TEST_VALUE"
            #$NewObject | Should -BeOfType StatusCreateRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
