#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'StatusScope' {
    Context 'StatusScope' {
        It 'Initialize-StatusScope' {
            # a simple test to create an object
            #$NewObject = Initialize-StatusScope -Type "TEST_VALUE" -Project "TEST_VALUE"
            #$NewObject | Should -BeOfType StatusScope
            #$NewObject.property | Should -Be 0
        }
    }
}
