#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'SuggestedIssue' {
    Context 'SuggestedIssue' {
        It 'Initialize-SuggestedIssue' {
            # a simple test to create an object
            #$NewObject = Initialize-SuggestedIssue -Id "TEST_VALUE" -Key "TEST_VALUE" -KeyHtml "TEST_VALUE" -Img "TEST_VALUE" -Summary "TEST_VALUE" -SummaryText "TEST_VALUE"
            #$NewObject | Should -BeOfType SuggestedIssue
            #$NewObject.property | Should -Be 0
        }
    }
}
