#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'TaskProgressBeanRemoveOptionFromIssuesResult' {
    Context 'TaskProgressBeanRemoveOptionFromIssuesResult' {
        It 'Initialize-TaskProgressBeanRemoveOptionFromIssuesResult' {
            # a simple test to create an object
            #$NewObject = Initialize-TaskProgressBeanRemoveOptionFromIssuesResult -Self "TEST_VALUE" -Id "TEST_VALUE" -Description "TEST_VALUE" -Status "TEST_VALUE" -Message "TEST_VALUE" -Result "TEST_VALUE" -SubmittedBy "TEST_VALUE" -Progress "TEST_VALUE" -ElapsedRuntime "TEST_VALUE" -Submitted "TEST_VALUE" -Started "TEST_VALUE" -Finished "TEST_VALUE" -LastUpdate "TEST_VALUE"
            #$NewObject | Should -BeOfType TaskProgressBeanRemoveOptionFromIssuesResult
            #$NewObject.property | Should -Be 0
        }
    }
}
