#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'TaskProgressBeanRemoveOptionFromIssuesResultResult' {
    Context 'TaskProgressBeanRemoveOptionFromIssuesResultResult' {
        It 'Initialize-TaskProgressBeanRemoveOptionFromIssuesResultResult' {
            # a simple test to create an object
            #$NewObject = Initialize-TaskProgressBeanRemoveOptionFromIssuesResultResult -ModifiedIssues "TEST_VALUE" -UnmodifiedIssues "TEST_VALUE" -Errors "TEST_VALUE"
            #$NewObject | Should -BeOfType TaskProgressBeanRemoveOptionFromIssuesResultResult
            #$NewObject.property | Should -Be 0
        }
    }
}
