#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Transition' {
    Context 'Transition' {
        It 'Initialize-Transition' {
            # a simple test to create an object
            #$NewObject = Initialize-Transition -Id "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -VarFrom "TEST_VALUE" -To "TEST_VALUE" -Type "TEST_VALUE" -Screen "TEST_VALUE" -Rules "TEST_VALUE" -Properties "TEST_VALUE"
            #$NewObject | Should -BeOfType Transition
            #$NewObject.property | Should -Be 0
        }
    }
}
