#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'UiModificationContextDetails' {
    Context 'UiModificationContextDetails' {
        It 'Initialize-UiModificationContextDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-UiModificationContextDetails -Id "TEST_VALUE" -ProjectId "TEST_VALUE" -IssueTypeId "TEST_VALUE" -ViewType "TEST_VALUE" -IsAvailable "TEST_VALUE"
            #$NewObject | Should -BeOfType UiModificationContextDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
