#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'UnrestrictedUserEmail' {
    Context 'UnrestrictedUserEmail' {
        It 'Initialize-UnrestrictedUserEmail' {
            # a simple test to create an object
            #$NewObject = Initialize-UnrestrictedUserEmail -AccountId "TEST_VALUE" -Email "TEST_VALUE"
            #$NewObject | Should -BeOfType UnrestrictedUserEmail
            #$NewObject.property | Should -Be 0
        }
    }
}
