#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'UpdateUserToGroupBean' {
    Context 'UpdateUserToGroupBean' {
        It 'Initialize-UpdateUserToGroupBean' {
            # a simple test to create an object
            #$NewObject = Initialize-UpdateUserToGroupBean -Name "TEST_VALUE" -AccountId "TEST_VALUE"
            #$NewObject | Should -BeOfType UpdateUserToGroupBean
            #$NewObject.property | Should -Be 0
        }
    }
}
