#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'UpdateProjectDetails' {
    Context 'UpdateProjectDetails' {
        It 'Initialize-UpdateProjectDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-UpdateProjectDetails -Key "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -Lead "TEST_VALUE" -LeadAccountId "TEST_VALUE" -Url "TEST_VALUE" -AssigneeType "TEST_VALUE" -AvatarId "TEST_VALUE" -IssueSecurityScheme "TEST_VALUE" -PermissionScheme "TEST_VALUE" -NotificationScheme "TEST_VALUE" -CategoryId "TEST_VALUE"
            #$NewObject | Should -BeOfType UpdateProjectDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
