#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'UserPermission' {
    Context 'UserPermission' {
        It 'Initialize-UserPermission' {
            # a simple test to create an object
            #$NewObject = Initialize-UserPermission -Id "TEST_VALUE" -Key "TEST_VALUE" -Name "TEST_VALUE" -Type "TEST_VALUE" -Description "TEST_VALUE" -HavePermission "TEST_VALUE" -DeprecatedKey "TEST_VALUE"
            #$NewObject | Should -BeOfType UserPermission
            #$NewObject.property | Should -Be 0
        }
    }
}
