#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'UserDetails' {
    Context 'UserDetails' {
        It 'Initialize-UserDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-UserDetails -Self "TEST_VALUE" -Name "TEST_VALUE" -Key "TEST_VALUE" -AccountId "TEST_VALUE" -EmailAddress "TEST_VALUE" -AvatarUrls "TEST_VALUE" -DisplayName "TEST_VALUE" -Active "TEST_VALUE" -TimeZone "TEST_VALUE" -AccountType "TEST_VALUE"
            #$NewObject | Should -BeOfType UserDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
