#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ValueOperand' {
    Context 'ValueOperand' {
        It 'Initialize-ValueOperand' {
            # a simple test to create an object
            #$NewObject = Initialize-ValueOperand -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType ValueOperand
            #$NewObject.property | Should -Be 0
        }
    }
}
