#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'VersionUnresolvedIssuesCount' {
    Context 'VersionUnresolvedIssuesCount' {
        It 'Initialize-VersionUnresolvedIssuesCount' {
            # a simple test to create an object
            #$NewObject = Initialize-VersionUnresolvedIssuesCount -Self "TEST_VALUE" -IssuesUnresolvedCount "TEST_VALUE" -IssuesCount "TEST_VALUE"
            #$NewObject | Should -BeOfType VersionUnresolvedIssuesCount
            #$NewObject.property | Should -Be 0
        }
    }
}
