#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Version' {
    Context 'Version' {
        It 'Initialize-Version' {
            # a simple test to create an object
            #$NewObject = Initialize-Version -Expand "TEST_VALUE" -Self "TEST_VALUE" -Id "TEST_VALUE" -Description "TEST_VALUE" -Name "TEST_VALUE" -Archived "TEST_VALUE" -Released "TEST_VALUE" -StartDate "TEST_VALUE" -ReleaseDate "TEST_VALUE" -Overdue "TEST_VALUE" -UserStartDate "TEST_VALUE" -UserReleaseDate "TEST_VALUE" -Project "TEST_VALUE" -ProjectId "TEST_VALUE" -MoveUnfixedIssuesTo "TEST_VALUE" -Operations "TEST_VALUE" -IssuesStatusForFixVersion "TEST_VALUE"
            #$NewObject | Should -BeOfType Version
            #$NewObject.property | Should -Be 0
        }
    }
}
