#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Votes' {
    Context 'Votes' {
        It 'Initialize-Votes' {
            # a simple test to create an object
            #$NewObject = Initialize-Votes -Self "TEST_VALUE" -Votes "TEST_VALUE" -HasVoted "TEST_VALUE" -Voters "TEST_VALUE"
            #$NewObject | Should -BeOfType Votes
            #$NewObject.property | Should -Be 0
        }
    }
}
