#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'WorkflowsWithTransitionRulesDetails' {
    Context 'WorkflowsWithTransitionRulesDetails' {
        It 'Initialize-WorkflowsWithTransitionRulesDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-WorkflowsWithTransitionRulesDetails -Workflows "TEST_VALUE"
            #$NewObject | Should -BeOfType WorkflowsWithTransitionRulesDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
