#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'WorkflowIDs' {
    Context 'WorkflowIDs' {
        It 'Initialize-WorkflowIDs' {
            # a simple test to create an object
            #$NewObject = Initialize-WorkflowIDs -Name "TEST_VALUE" -EntityId "TEST_VALUE"
            #$NewObject | Should -BeOfType WorkflowIDs
            #$NewObject.property | Should -Be 0
        }
    }
}
