#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'WorkflowTransitionRulesUpdateErrorDetails' {
    Context 'WorkflowTransitionRulesUpdateErrorDetails' {
        It 'Initialize-WorkflowTransitionRulesUpdateErrorDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-WorkflowTransitionRulesUpdateErrorDetails -WorkflowId "TEST_VALUE" -RuleUpdateErrors "TEST_VALUE" -UpdateErrors "TEST_VALUE"
            #$NewObject | Should -BeOfType WorkflowTransitionRulesUpdateErrorDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
