#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Workflow' {
    Context 'Workflow' {
        It 'Initialize-Workflow' {
            # a simple test to create an object
            #$NewObject = Initialize-Workflow -Id "TEST_VALUE" -Description "TEST_VALUE" -Transitions "TEST_VALUE" -Statuses "TEST_VALUE" -IsDefault "TEST_VALUE" -Schemes "TEST_VALUE" -Projects "TEST_VALUE" -HasDraftWorkflow "TEST_VALUE" -Operations "TEST_VALUE" -Created "TEST_VALUE" -Updated "TEST_VALUE"
            #$NewObject | Should -BeOfType Workflow
            #$NewObject.property | Should -Be 0
        }
    }
}
