#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'WorkManagementNavigationInfo' {
    Context 'WorkManagementNavigationInfo' {
        It 'Initialize-WorkManagementNavigationInfo' {
            # a simple test to create an object
            #$NewObject = Initialize-WorkManagementNavigationInfo -BoardName "TEST_VALUE"
            #$NewObject | Should -BeOfType WorkManagementNavigationInfo
            #$NewObject.property | Should -Be 0
        }
    }
}
