#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'WorkflowRulesSearch' {
    Context 'WorkflowRulesSearch' {
        It 'Initialize-WorkflowRulesSearch' {
            # a simple test to create an object
            #$NewObject = Initialize-WorkflowRulesSearch -WorkflowEntityId "TEST_VALUE" -RuleIds "TEST_VALUE" -Expand "TEST_VALUE"
            #$NewObject | Should -BeOfType WorkflowRulesSearch
            #$NewObject.property | Should -Be 0
        }
    }
}
