#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'WorkflowScheme' {
    Context 'WorkflowScheme' {
        It 'Initialize-WorkflowScheme' {
            # a simple test to create an object
            #$NewObject = Initialize-WorkflowScheme -Id "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -DefaultWorkflow "TEST_VALUE" -IssueTypeMappings "TEST_VALUE" -OriginalDefaultWorkflow "TEST_VALUE" -OriginalIssueTypeMappings "TEST_VALUE" -Draft "TEST_VALUE" -LastModifiedUser "TEST_VALUE" -LastModified "TEST_VALUE" -Self "TEST_VALUE" -UpdateDraftIfNeeded "TEST_VALUE" -IssueTypes "TEST_VALUE"
            #$NewObject | Should -BeOfType WorkflowScheme
            #$NewObject.property | Should -Be 0
        }
    }
}
