#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'WorkflowRulesSearchDetails' {
    Context 'WorkflowRulesSearchDetails' {
        It 'Initialize-WorkflowRulesSearchDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-WorkflowRulesSearchDetails -WorkflowEntityId "TEST_VALUE" -InvalidRules "TEST_VALUE" -ValidRules "TEST_VALUE"
            #$NewObject | Should -BeOfType WorkflowRulesSearchDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
