#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'WorkflowStatus' {
    Context 'WorkflowStatus' {
        It 'Initialize-WorkflowStatus' {
            # a simple test to create an object
            #$NewObject = Initialize-WorkflowStatus -Id "TEST_VALUE" -Name "TEST_VALUE" -Properties "TEST_VALUE"
            #$NewObject | Should -BeOfType WorkflowStatus
            #$NewObject.property | Should -Be 0
        }
    }
}
