#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'WorkflowId' {
    Context 'WorkflowId' {
        It 'Initialize-WorkflowId' {
            # a simple test to create an object
            #$NewObject = Initialize-WorkflowId -Name "TEST_VALUE" -Draft "TEST_VALUE"
            #$NewObject | Should -BeOfType WorkflowId
            #$NewObject.property | Should -Be 0
        }
    }
}
