#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'WorklogIdsRequestBean' {
    Context 'WorklogIdsRequestBean' {
        It 'Initialize-WorklogIdsRequestBean' {
            # a simple test to create an object
            #$NewObject = Initialize-WorklogIdsRequestBean -Ids "TEST_VALUE"
            #$NewObject | Should -BeOfType WorklogIdsRequestBean
            #$NewObject.property | Should -Be 0
        }
    }
}
